version: '3.3'
services:

  db:
    image: postgres:13.10-alpine 
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    image: waffe1n/foodgram_backend_app:latest
    restart: always
    volumes:
      - static_backend:/app/static/
      - media_backend:/app/media/
    depends_on:
      - db
    ports:
      - '8000:8000'
    env_file:
      - ./.env

  frontend:
    image: waffe1n/foodgram_frontend
    volumes:
      - ../frontend/:/app/build/
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static
      - media:/var/html/media
    depends_on:
      - backend
      - frontend
    restart: always
